theme: jekyll-theme-minimal
title: Mahe-Lab Standard Operating Procedures
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
